In [19]:
# internal modules
from color_brains.data.sequential_data import SequentialData
import pandas as pd
import numpy as np
from typing import *

In [20]:
sd = SequentialData()
df = sd.dataset
feature_df = df
df.head()

      colormap_name       red     green      blue
0  sequential.Greys  1.000000  1.000000  1.000000
1  sequential.Greys  0.998155  0.998155  0.998155
2  sequential.Greys  0.996309  0.996309  0.996309
3  sequential.Greys  0.994464  0.994464  0.994464
4  sequential.Greys  0.992618  0.992618  0.992618

In [21]:
rgb_columns = [c for c in df.columns if c != sd.CmapNameColumn]
def mangle_rgb_names(tag: str) -> List[str]:
    return [f'{tag}_{column}' for column in rgb_columns]
rgb_columns

['red', 'green', 'blue']

In [22]:
# starting rgb
prev_rgb = feature_df.groupby([sd.CmapNameColumn]).shift(1).reset_index(drop=True)
prev_rgb.columns = mangle_rgb_names("previous")
feature_df = feature_df.join(prev_rgb)
feature_df.head()

,colormap_name,red,green,blue,previous_red,previous_green,previous_blue
0,sequential.Greys,1.000000,1.000000,1.000000,NaN,NaN,NaN
1,sequential.Greys,0.998155,0.998155,0.998155,1.000000,1.000000,1.000000
2,sequential.Greys,0.996309,0.996309,0.996309,0.998155,0.998155,0.998155
3,sequential.Greys,0.994464,0.994464,0.994464,0.996309,0.996309,0.996309
4,sequential.Greys,0.992618,0.992618,0.992618,0.994464,0.994464,0.994464

In [23]:
# squareroots of current rgb 
sqrt_df =  np.sqrt(feature_df[rgb_columns])
sqrt_df.columns = mangle_rgb_names("sqrt")
feature_df = feature_df.join(sqrt_df)

# cuberoots of current rgb
cuberoot_df =  np.sqrt(feature_df[rgb_columns])
cuberoot_df.columns = mangle_rgb_names("cbrt")
feature_df = feature_df.join(cuberoot_df)

feature_df.head()

,colormap_name,red,green,blue,previous_red,previous_green,previous_blue,sqrt_red,sqrt_green,sqrt_blue,cbrt_red,cbrt_green,cbrt_blue
0,sequential.Greys,1.000000,1.000000,1.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,sequential.Greys,0.998155,0.998155,0.998155,1.000000,1.000000,1.000000,0.999077,0.999077,0.999077,0.999077,0.999077,0.999077
2,sequential.Greys,0.996309,0.996309,0.996309,0.998155,0.998155,0.998155,0.998153,0.998153,0.998153,0.998153,0.998153,0.998153
3,sequential.Greys,0.994464,0.994464,0.994464,0.996309,0.996309,0.996309,0.997228,0.997228,0.997228,0.997228,0.997228,0.997228
4,sequential.Greys,0.992618,0.992618,0.992618,0.994464,0.994464,0.994464,0.996302,0.996302,0.996302,0.996302,0.996302,0.996302

In [40]:
# rgb of start of sequence
start_rgb = df.groupby(sd.CmapNameColumn).nth(0)
start_rgb = start_rgb.set_index(sd.CmapNameColumn)
start_rgb.columns = mangle_rgb_names("first")
feature_df = pd.merge(feature_df, start_rgb, how='left', on=[sd.CmapNameColumn])
feature_df.head()

,colormap_name,red,green,blue,previous_red,previous_green,previous_blue,sqrt_red,sqrt_green,sqrt_blue,cbrt_red,cbrt_green,cbrt_blue,first_red,first_green,first_blue
0,sequential.Greys,1.000000,1.000000,1.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0,1.0
1,sequential.Greys,0.998155,0.998155,0.998155,1.000000,1.000000,1.000000,0.999077,0.999077,0.999077,0.999077,0.999077,0.999077,1.0,1.0,1.0
2,sequential.Greys,0.996309,0.996309,0.996309,0.998155,0.998155,0.998155,0.998153,0.998153,0.998153,0.998153,0.998153,0.998153,1.0,1.0,1.0
3,sequential.Greys,0.994464,0.994464,0.994464,0.996309,0.996309,0.996309,0.997228,0.997228,0.997228,0.997228,0.997228,0.997228,1.0,1.0,1.0
4,sequential.Greys,0.992618,0.992618,0.992618,0.994464,0.994464,0.994464,0.996302,0.996302,0.996302,0.996302,0.996302,0.996302,1.0,1.0,1.0

           colormap_name       red     green      blue
25088  cartomap.BluGrn_7  0.768627  0.901961  0.764706
25089  cartomap.BluGrn_7  0.764383  0.900115  0.761845
25090  cartomap.BluGrn_7  0.760138  0.898270  0.758985
25091  cartomap.BluGrn_7  0.755894  0.896424  0.756125
25092  cartomap.BluGrn_7  0.751649  0.894579  0.753264
...                  ...       ...       ...       ...
25339  cartomap.BluGrn_7  0.117047  0.320138  0.381638
25340  cartomap.BluGrn_7  0.116217  0.317555  0.380346
25341  cartomap.BluGrn_7  0.115386  0.314971  0.379054
25342  cartomap.BluGrn_7  0.114556  0.312388  0.377762
25343  cartomap.BluGrn_7  0.113725  0.309804  0.376471

[256 rows x 4 columns]